spring.application.name=careerconnect
# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/careerconnect
spring.datasource.username=root
spring.datasource.password=Admin@123

# Hibernate Magic (Ye DB mein tables apne aap banayega)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true